// // get.ArrayType();
// // array();
// // toArray();
// // clone();
// // set();
// // at();
// // slice();
// // push();
// // pop();
// unshift();
// // shift();
// // sort();
// // reverse();
// // fill();
// // indexOf();
// // lastIndexOf();
// // includes();
// // findIndex();
// // findLast();
// // findLastIndex();
// // every();
// // some();
// // filter();
// // map();
// // forEach();
// // reduce();
// // reduceRight();
// // join();
// // reduceMemory();
// #grow();
// // #shrink();

const NumArray = require("./main");

var arr = NumArray("int32", 10).map((x) => x + 1);
// for (var i = 0; i < 10; ++i) arr.push(i + 1);
// for (var i = 0; i < 10; ++i) arr.unshift(i + 1);
console.log(arr);
